#ifndef S_CONFIG_H
#define S_CONFIG_H

enum {
    SPOOR_DEFAULT_FONT_SIZE,
};

#define CONFIG_DEFAULT_FONT_SIZE config_font_sizes[SPOOR_DEFAULT_FONT_SIZE]
#define CONFIG_DEFAULT_FONT_SIZE_SET(font_size) config_font_sizes[SPOOR_DEFAULT_FONT_SIZE] = font_size

/* color current day 0x552588 55 alpha*/

u32 config_font_sizes[] = {
    13
};

enum {
    SPOOR_COLOR_FOREGROUND,
    SPOOR_COLOR_BACKGROUND,
    SPOOR_COLOR_CALENDAR_OBJECT_OUTLINE,
    SPOOR_COLOR_CALENDAR_OBJECT_OUTLINE_MARKED,
    SPOOR_COLOR_CALENDAR_OBJECT_BACKGROUND,
    SPOOR_COLOR_CALENDAR_OBJECT_OUTLINE_GRABED,
};

#define CONFIG_COLOR_FOREGROUND config_colors[SPOOR_COLOR_FOREGROUND]
#define CONFIG_COLOR_FOREGROUND_SET(color) config_colors[SPOOR_COLOR_FOREGROUND] = color

#define CONFIG_COLOR_BACKGROUND config_colors[SPOOR_COLOR_BACKGROUND]
#define CONFIG_COLOR_BACKGROUND_SET(color) config_colors[SPOOR_COLOR_BACKGROUND] = color

#define CONFIG_COLOR_CALENDAR_OBJECT_OUTLINE config_colors[SPOOR_COLOR_CALENDAR_OBJECT_OUTLINE]
#define CONFIG_COLOR_CALENDAR_OBJECT_OUTLINE_SET(color) config_colors[SPOOR_COLOR_CALENDAR_OBJECT_OUTLINE] = color

#define CONFIG_COLOR_CALENDAR_OBJECT_OUTLINE_MARKED config_colors[SPOOR_COLOR_CALENDAR_OBJECT_OUTLINE_MARKED]
#define CONFIG_COLOR_CALENDAR_OBJECT_OUTLINE_MARKED_SET(color) config_colors[SPOOR_COLOR_CALENDAR_OBJECT_OUTLINE_MARKED] = color

#define CONFIG_COLOR_CALENDAR_OBJECT_BACKGROUND config_colors[SPOOR_COLOR_CALENDAR_OBJECT_BACKGROUND]
#define CONFIG_COLOR_CALENDAR_OBJECT_BACKGROUND_SET(color) config_colors[SPOOR_COLOR_CALENDAR_OBJECT_BACKGROUND] = color

#define CONFIG_COLOR_CALENDAR_OBJECT_OUTLINE_GRABED config_colors[SPOOR_COLOR_CALENDAR_OBJECT_OUTLINE_GRABED]
#define CONFIG_COLOR_CALENDAR_OBJECT_OUTLINE_GRABED_SET(color) config_colors[SPOOR_COLOR_CALENDAR_OBJECT_OUTLINE_GRABED] = color


u32 config_colors[] = {
    0xff000000,
    0xffd3b083, /* Background */
    0xff000000,
    0xffffffff,
    0x88665577,
    0xff556610,
};


/* CONFIG STATUS BAR */
enum {
    SPOOR_STATUS_BAR_HEIGHT,
    SPOOR_STATUS_BAR_PADDING,
    SPOOR_COLOR_STATUS_BAR_FOREGROUND,
    SPOOR_COLOR_STATUS_BAR_BACKGROUND,
};

#define CONFIG_STATUS_BAR_HEIGHT config_status_bar[SPOOR_STATUS_BAR_HEIGHT]
#define CONFIG_STATUS_BAR_HEIGHT_SET(height) config_status_bar[SPOOR_STATUS_BAR_HEIGHT] = height

#define CONFIG_STATUS_BAR_PADDING config_status_bar[SPOOR_STATUS_BAR_PADDING]
#define CONFIG_STATUS_BAR_PADDING_SET(padding) config_status_bar[SPOOR_STATUS_BAR_PADDING] = padding

#define CONFIG_COLOR_STATUS_BAR_BACKGROUND config_status_bar[SPOOR_COLOR_STATUS_BAR_BACKGROUND]
#define CONFIG_COLOR_STATUS_BAR_BACKGROUND_SET(color) config_status_bar[COLOR_STATUS_BAR_BACKGROUND] = color

#define CONFIG_COLOR_STATUS_BAR_FOREGROUND config_status_bar[SPOOR_COLOR_STATUS_BAR_FOREGROUND]
#define CONFIG_COLOR_STATUS_BAR_FOREGROUND_SET(color) config_status_bar[SPOOR_COLOR_STATUS_BAR_FOREGROUND] = color

u32 config_status_bar[] = {
    30,
    2,
    0xff000000,
    0xeeeeeeee,
};

enum {
    SPOOR_GRAPHIC_SCALE,
};

#define CONFIG_GRAPHIC_SCALE config_graphic[SPOOR_GRAPHIC_SCALE]
#define CONFIG_GRAPHIC_SCALE_SET(scale) config_graphic[SPOOR_GRAPHIC_SCALE] = scale;

float config_graphic[] = {
    1,
};

/* CONFIG VIEW */
enum {
    SPOOR_VIEW_BORDER_SIZE,
    SPOOR_VIEW_GAP_SIZE,
    SPOOR_VIEW_BORDER_COLOR,
};

#define CONFIG_VIEW_BORDER_SIZE config_view[SPOOR_VIEW_BORDER_SIZE]
#define CONFIG_VIEW_BORDER_SIZE_SET(border_size) config_view[SPOOR_VIEW_BORDER_SIZE] = border_size

#define CONFIG_VIEW_GAP_SIZE config_view[SPOOR_VIEW_GAP_SIZE]
#define CONFIG_VIEW_GAP_SIZE_SET(gap_size) config_view[SPOOR_VIEW_GAP_SIZE] = gap_size

#define CONFIG_VIEW_BORDER_COLOR config_view[SPOOR_VIEW_BORDER_COLOR]
#define CONFIG_VIEW_BORDER_COLOR_SET(border_color) config_view[SPOOR_VIEW_BORDER_COLOR] = border_color

u32 config_view[] = {
    2,
    4,
    0xffffffff,
};

/* status colors */
const u32 CONFIG_COLOR_STATUS[3] = {
    0xff551100,
    0xff887722,
    0xff228811,
};

#endif
