#ifndef S_CONFIG_H
#define S_CONFIG_H

enum {
    SPOOR_COLOR_BACKGROUND,
    SPOOR_COLOR_FOREGROUND,
};

#define CONFIG_COLOR_BACKGROUND config_colors[SPOOR_COLOR_BACKGROUND]
#define CONFIG_COLOR_BACKGROUND_SET(color) config_colors[SPOOR_COLOR_BACKGROUND] = color

#define CONFIG_COLOR_FOREGROUND config_colors[SPOOR_COLOR_FOREGROUND]
#define CONFIG_COLOR_FOREGROUND_SET(color) config_colors[SPOOR_COLOR_BACKGROUND] = color

u32 config_colors[] = {
    0xff0c0c0c,
    0xffa08563,
};

/* CONFIG STATUS BAR */
enum {
    SPOOR_STATUS_BAR_HEIGHT,
    SPOOR_STATUS_BAR_PADDING,
    SPOOR_COLOR_STATUS_BAR_BACKGROUND,
    SPOOR_COLOR_STATUS_BAR_FOREGROUND,
};

#define CONFIG_STATUS_BAR_HEIGHT config_status_bar[SPOOR_STATUS_BAR_HEIGHT]
#define CONFIG_STATUS_BAR_HEIGHT_SET(height) config_status_bar[SPOOR_STATUS_BAR_HEIGHT] = height

#define CONFIG_STATUS_BAR_PADDING config_status_bar[SPOOR_STATUS_BAR_PADDING]
#define CONFIG_STATUS_BAR_PADDING_SET(padding) config_status_bar[SPOOR_STATUS_BAR_PADDING] = padding

#define CONFIG_COLOR_STATUS_BAR_BACKGROUND config_status_bar[SPOOR_COLOR_STATUS_BAR_BACKGROUND]
#define CONFIG_COLOR_STATUS_BAR_BACKGROUND_SET(color) config_status_bar[COLOR_STATUS_BAR_BACKGROUND] = color

#define CONFIG_COLOR_STATUS_BAR_FOREGROUND config_status_bar[SPOOR_COLOR_STATUS_BAR_FOREGROUND]
#define CONFIG_COLOR_STATUS_BAR_FOREGROUND_SET(color) config_status_bar[SPOOR_COLOR_STATUS_BAR_FOREGROUND] = color

u32 config_status_bar[] = {
    30,
    2,
    0x11a08563,
    0xffa08563,
};

enum {
    SPOOR_GRAPHIC_SCALE,
};

#define CONFIG_GRAPHIC_SCALE config_graphic[SPOOR_GRAPHIC_SCALE]
#define CONFIG_GRAPHIC_SCALE_SET(scale) config_graphic[SPOOR_GRAPHIC_SCALE] = scale;

float config_graphic[] = {
    1,
};

#endif
