int settings_count = 0;

#define CONFIG_NEW(name, value, type) type CONFIG_##name = value
#define CONFIG(name) CONFIG_##name
#define CONFIG_SET(name, value) CONFIG_##name = value

CONFIG_NEW(COLOR_FOREGROUND, 0xff000000, u32);
CONFIG_NEW(COLOR_BACKGROUND, 0xffd3b083, u32);

CONFIG_NEW(STATUS_BAR_COLOR_FOREGROUND, 0xff000000, u32);
CONFIG_NEW(STATUS_BAR_COLOR_BACKGROUND, 0xeeeeeeee, u32);
CONFIG_NEW(STATUS_BAR_FONT_SIZE, 30, u16);
CONFIG_NEW(STATUS_BAR_HEIGHT, 50, u32);
CONFIG_NEW(STATUS_BAR_PADDING, 2, u32);

CONFIG_NEW(FONT_SCALE, 1, float);
CONFIG_NEW(FONT_DEFAULT_SIZE, 13, u32);

CONFIG_NEW(VIEW_GAP, 4, u32);
CONFIG_NEW(VIEW_BORDER_WIDTH, 4, u32);
CONFIG_NEW(VIEW_BORDER_COLOR, 0xffffffff, u32);

CONFIG_NEW(CALENDAR_OBJECT_COLOR_BACKGROUND, 0xffd3b083, u32);
CONFIG_NEW(CALENDAR_OBJECT_OUTLINE_COLOR, 0xff000000, u32);
CONFIG_NEW(CALENDAR_OBJECT_OUTLINE_GRABED_COLOR, 0xff556610, u32);
CONFIG_NEW(CALENDAR_OBJECT_OUTLINE_MARKED_COLOR, 0xffffffff, u32);

CONFIG_NEW(TASK_LIST_INFO_BAR_COLOR_FOREGROUND, 0xffffffff, u32);
CONFIG_NEW(TASK_LIST_INFO_BAR_COLOR_BACKGROUND, 0xff734023, u32);
