#ifndef S_INPUT_H
#define S_INPUT_H

#define SPOOR_INPUT_ASCII_KEY_RETURN 0x0d
#define SPOOR_INPUT_ASCII_KEY_BACKSPACE 0x08
#define SPOOR_INPUT_ASCII_KEY_CONTROL_S 0x13
#define SPOOR_INPUT_ASCII_KEY_CONTROL_H 0x08
#define SPOOR_INPUT_ASCII_KEY_CONTROL_U 0x15
#define SPOOR_INPUT_ASCII_KEY_CONTROL_D 0x04


#endif
